### ISSUE TITLE
如果输入是关键词列表

### ISSUE THREAD

**Issue by wanghaisheng** [Shadow-Alex/PaperCrawler#2]
我该改哪里 没有太看懂

**Comment by Shadow-Alex** [comment]
> 我该改哪里 没有太看懂

您说的关键词是放在advance search这里的keywords嘛？
![image](https://github.com/Shadow-Alex/PaperCrawler/assets/46802674/d160d9c2-15b0-47ff-9c1d-793b3f4ac77e)

**Comment by wanghaisheng** [comment]
我自己弄了一个buildurl方法  下面那里根据list文件名判断一下 搞定了

**Comment by Shadow-Alex** [comment]
> 我自己弄了一个buildurl方法 下面那里根据list文件名判断一下 搞定了

嗯嗯，量小的话直接根据需要buildurl就可以了，量大的话每次buildurl直接访问会由于没有引荐页增加bot check的概率

**Comment by wanghaisheng** [comment]
我引入了一个capcha solver

**Comment by Shadow-Alex** [comment]
> 我引入了一个capcha solver

有推荐么？

**Comment by wanghaisheng** [comment]
recaptcha-challenger

https://github.com/ai4ecd/hine-latest-paper

**Comment by Shadow-Alex** [comment]
> recaptcha-challenger
> 
> https://github.com/ai4ecd/hine-latest-paper

美妙，十分感谢，改成用openai的whisper效果更好了。

**Comment by wanghaisheng** [comment]
如果文献这里 只选最近一周、一月、一年的话 你能不能写一下 哈哈

**Comment by Shadow-Alex** [comment]
我调研了下，google scholar是不支持精度小于1年的，它advance search只能到年度。

如果需要更细粒度的话，可能需要先按照年度来索引，然后去出版社的详情页中去找，我写一下详情页的逻辑，把doi也爬了。

**Comment by wanghaisheng** [comment]
那就年吧，定期爬，完了以后，我把dump的数据再做一下过滤和比对，
你看我从别人那里搞了一个
https://github.com/wanghaisheng/arxiv-paper-daily

有了你这个，我相当于就覆盖了 paper latest monitoring这个任务了

我最主要还是根据关键词走，你为啥要做journal，这个面不是太广太杂了吗

**Comment by wanghaisheng** [comment]
可以弄一个默认起始年，现在是1990

**Comment by Shadow-Alex** [comment]
> 我最主要还是根据关键词走，你为啥要做journal，这个面不是太广太杂了吗

主要是为了支撑我一个NLP mining的研究，这部分是构造数据集准备的爬虫，mining和filter的逻辑我就没放在这里。

> 我看你已经做了一个根据pickle文件的连续爬取，以天、以月、周为定时爬取的周期，其实就已经能拿到这周的更新情况，不知道我理解对不对

可以这么理解，对于新文章的话，一般paper的publish很快就能在scholar上搜索到，因此我觉得是可以把gs出现时间当作publish时间的。

最初做分年爬是因为google scholar最多返回1000个搜索结果（10x100page），即便有更多的满足条件。

**Comment by wanghaisheng** [comment]
懂了懂了
最终其实publish时间对我们意义不大，能获取的时间才是真时间 哈哈
